language: cpp

jobs:
  include:
    - os: windows
    - os: osx
    - os: linux
      dist: bionic

notifications:
  email: false

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then bash preLinux.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then bash preMacOS.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then cmd.exe "/q /c preWindows.bat"; fi

script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then bash build.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then bash build.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then cmd.exe "/q /c build.bat"; fi

after_success:
  - echo "Build Successfull!"